!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_gmdpd_f_randd (randdf2pywrap)
      use gmdpd_f, only : randd
      real(kind=8) randdf2pywrap
      randdf2pywrap = randd()
      end subroutine f2pywrap_gmdpd_f_randd
      subroutine f2pywrap_gmdpd_f_wr (wrf2pywrap, nr)
      use gmdpd_f, only : wr
      real(kind=8) nr
      real(kind=8) wrf2pywrap
      wrf2pywrap = wr(nr)
      end subroutine f2pywrap_gmdpd_f_wr
      subroutine f2pywrap_gmdpd_f_wdd (wddf2pywrap, nr, rd)
      use gmdpd_f, only : wdd
      real(kind=8) nr
      real(kind=8) rd
      real(kind=8) wddf2pywrap
      wddf2pywrap = wdd(nr, rd)
      end subroutine f2pywrap_gmdpd_f_wdd
      subroutine f2pywrap_gmdpd_f_gaussnum (gaussnumf2pywrap)
      use gmdpd_f, only : gaussnum
      real(kind=8) gaussnumf2pywrap
      gaussnumf2pywrap = gaussnum()
      end subroutine f2pywrap_gmdpd_f_gaussnum
      subroutine f2pywrap_gmdpd_f_local_density (local_densityf2pywrap, &
     &X, bl, nbt, rd, box, f2py_X_d0, f2py_X_d1, f2py_bl_d0, f2py_rd_d0,&
     & f2py_rd_d1)
      use gmdpd_f, only : local_density
      integer nbt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_bl_d0
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      real(kind=8) local_densityf2pywrap(size(X, 1),nbt)
      local_densityf2pywrap = local_density(X, bl, nbt, rd, box)
      end subroutine f2pywrap_gmdpd_f_local_density
      subroutine f2pywrap_gmdpd_f_compute_force_fun (compute_force_funf2&
     &pywrap, X, V, rho2, bl, ip_a, ip_b, rd, box, gama, kT, dt, f2py_X_&
     &d0, f2py_X_d1, f2py_V_d0, f2py_V_d1, f2py_rho2_d0, f2py_rho2_d1, f&
     &2py_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2py_rd_d0, f2py_rd_d1)
      use gmdpd_f, only : compute_force_fun
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      real(kind=8) compute_force_funf2pywrap(size(X, 1),3)
      compute_force_funf2pywrap = compute_force_fun(X, V, rho2, bl, ip_a&
     &, ip_b, rd, box, gama, kT, dt)
      end subroutine f2pywrap_gmdpd_f_compute_force_fun
      subroutine f2pywrap_gmdpd_f_compute_force (F, vir, sigma, X, V, rh&
     &o2, bl, ip_a, ip_b, rd, box, gama, kT, dt, f2py_F_d0, f2py_F_d1, f&
     &2py_X_d0, f2py_X_d1, f2py_V_d0, f2py_V_d1, f2py_rho2_d0, f2py_rho2&
     &_d1, f2py_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2py_rd_d0, f2py_rd_d&
     &1)
      use gmdpd_f, only : compute_force
      real(kind=8) vir
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_F_d0
      integer f2py_F_d1
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) F(f2py_F_d0,f2py_F_d1)
      real(kind=8) sigma(3)
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      call compute_force(F, vir, sigma, X, V, rho2, bl, ip_a, ip_b, rd, &
     &box, gama, kT, dt)
      end subroutine f2pywrap_gmdpd_f_compute_force
      subroutine f2pywrap_gmdpd_f_compute_force_cube (compute_force_cube&
     &f2pywrap, X, V, rho2, bl, ip_a, ip_b, rd, box, gama, kT, dt, f2py_&
     &X_d0, f2py_X_d1, f2py_V_d0, f2py_V_d1, f2py_rho2_d0, f2py_rho2_d1,&
     & f2py_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2py_rd_d0, f2py_rd_d1)
      use gmdpd_f, only : compute_force_cube
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      real(kind=8) compute_force_cubef2pywrap(size(X, 1),size(X, 1),3)
      compute_force_cubef2pywrap = compute_force_cube(X, V, rho2, bl, ip&
     &_a, ip_b, rd, box, gama, kT, dt)
      end subroutine f2pywrap_gmdpd_f_compute_force_cube
      subroutine f2pywrap_gmdpd_f_compute_pe (compute_pef2pywrap, X, rho&
     &2, bl, ip_a, ip_b, rd, box, f2py_X_d0, f2py_X_d1, f2py_rho2_d0, f2&
     &py_rho2_d1, f2py_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2py_rd_d0, f2&
     &py_rd_d1)
      use gmdpd_f, only : compute_pe
      real(kind=8) ip_b
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      real(kind=8) compute_pef2pywrap
      compute_pef2pywrap = compute_pe(X, rho2, bl, ip_a, ip_b, rd, box)
      end subroutine f2pywrap_gmdpd_f_compute_pe
      subroutine f2pywrap_gmdpd_f_compute_ke (compute_kef2pywrap, V, f2p&
     &y_V_d0, f2py_V_d1)
      use gmdpd_f, only : compute_ke
      integer f2py_V_d0
      integer f2py_V_d1
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) compute_kef2pywrap
      compute_kef2pywrap = compute_ke(V)
      end subroutine f2pywrap_gmdpd_f_compute_ke
      subroutine f2pywrap_gmdpd_f_init_pos (init_posf2pywrap, N, box)
      use gmdpd_f, only : init_pos
      integer N
      real(kind=8) box(3,3)
      real(kind=8) init_posf2pywrap(N,3)
      init_posf2pywrap = init_pos(N, box)
      end subroutine f2pywrap_gmdpd_f_init_pos
      subroutine f2pywrap_gmdpd_f_init_vel (init_velf2pywrap, N, kT)
      use gmdpd_f, only : init_vel
      integer N
      real(kind=8) kT
      real(kind=8) init_velf2pywrap(N,3)
      init_velf2pywrap = init_vel(N, kT)
      end subroutine f2pywrap_gmdpd_f_init_vel
      subroutine f2pywrap_gmdpd_f_euler_step (X, V, rho2, bl, nbt, ip_a,&
     & ip_b, rd, box, gama, kT, dt, f2py_X_d0, f2py_X_d1, f2py_V_d0, f2p&
     &y_V_d1, f2py_rho2_d0, f2py_rho2_d1, f2py_bl_d0, f2py_ip_a_d0, f2py&
     &_ip_a_d1, f2py_rd_d0, f2py_rd_d1)
      use gmdpd_f, only : euler_step
      integer nbt
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      call euler_step(X, V, rho2, bl, nbt, ip_a, ip_b, rd, box, gama, kT&
     &, dt)
      end subroutine f2pywrap_gmdpd_f_euler_step
      subroutine f2pywrap_gmdpd_f_verlet_step (X, V, F, rho2, bl, nbt, i&
     &p_a, ip_b, rd, box, gama, kT, dt, f2py_X_d0, f2py_X_d1, f2py_V_d0,&
     & f2py_V_d1, f2py_F_d0, f2py_F_d1, f2py_rho2_d0, f2py_rho2_d1, f2py&
     &_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2py_rd_d0, f2py_rd_d1)
      use gmdpd_f, only : verlet_step
      integer nbt
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_F_d0
      integer f2py_F_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) F(f2py_F_d0,f2py_F_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      call verlet_step(X, V, F, rho2, bl, nbt, ip_a, ip_b, rd, box, gama&
     &, kT, dt)
      end subroutine f2pywrap_gmdpd_f_verlet_step
      subroutine f2pywrap_gmdpd_f_print_mat (A, f2py_A_d0, f2py_A_d1)
      use gmdpd_f, only : print_mat
      integer f2py_A_d0
      integer f2py_A_d1
      real(kind=8) A(f2py_A_d0,f2py_A_d1)
      call print_mat(A)
      end subroutine f2pywrap_gmdpd_f_print_mat
      
      subroutine f2pyinitgmdpd_f(f2pysetupfunc)
      interface 
      subroutine f2pywrap_gmdpd_f_randd (randdf2pywrap, randd)
      real(kind=8) randd
      real(kind=8) randdf2pywrap
      end subroutine f2pywrap_gmdpd_f_randd 
      subroutine f2pywrap_gmdpd_f_wr (wrf2pywrap, wr, nr)
      real(kind=8) wr
      real(kind=8) nr
      real(kind=8) wrf2pywrap
      end subroutine f2pywrap_gmdpd_f_wr 
      subroutine f2pywrap_gmdpd_f_wdd (wddf2pywrap, wdd, nr, rd)
      real(kind=8) wdd
      real(kind=8) nr
      real(kind=8) rd
      real(kind=8) wddf2pywrap
      end subroutine f2pywrap_gmdpd_f_wdd 
      subroutine f2pywrap_gmdpd_f_gaussnum (gaussnumf2pywrap, gaussnum)
      real(kind=8) gaussnum
      real(kind=8) gaussnumf2pywrap
      end subroutine f2pywrap_gmdpd_f_gaussnum 
      subroutine f2pywrap_gmdpd_f_local_density (local_densityf2pywrap, &
     &local_density, X, bl, nbt, rd, box, f2py_X_d0, f2py_X_d1, f2py_bl_&
     &d0, f2py_rd_d0, f2py_rd_d1)
      integer nbt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_bl_d0
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      real(kind=8) local_density(size(X, 1),nbt)
      real(kind=8) local_densityf2pywrap(size(X, 1),nbt)
      end subroutine f2pywrap_gmdpd_f_local_density 
      subroutine f2pywrap_gmdpd_f_compute_force_fun (compute_force_funf2&
     &pywrap, compute_force_fun, X, V, rho2, bl, ip_a, ip_b, rd, box, ga&
     &ma, kT, dt, f2py_X_d0, f2py_X_d1, f2py_V_d0, f2py_V_d1, f2py_rho2_&
     &d0, f2py_rho2_d1, f2py_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2py_rd_&
     &d0, f2py_rd_d1)
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      real(kind=8) compute_force_fun(size(X, 1),3)
      real(kind=8) compute_force_funf2pywrap(size(X, 1),3)
      end subroutine f2pywrap_gmdpd_f_compute_force_fun 
      subroutine f2pywrap_gmdpd_f_compute_force (F, vir, sigma, X, V, rh&
     &o2, bl, ip_a, ip_b, rd, box, gama, kT, dt, f2py_F_d0, f2py_F_d1, f&
     &2py_X_d0, f2py_X_d1, f2py_V_d0, f2py_V_d1, f2py_rho2_d0, f2py_rho2&
     &_d1, f2py_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2py_rd_d0, f2py_rd_d&
     &1)
      real(kind=8) vir
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_F_d0
      integer f2py_F_d1
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) F(f2py_F_d0,f2py_F_d1)
      real(kind=8) sigma(3)
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      end subroutine f2pywrap_gmdpd_f_compute_force 
      subroutine f2pywrap_gmdpd_f_compute_force_cube (compute_force_cube&
     &f2pywrap, compute_force_cube, X, V, rho2, bl, ip_a, ip_b, rd, box,&
     & gama, kT, dt, f2py_X_d0, f2py_X_d1, f2py_V_d0, f2py_V_d1, f2py_rh&
     &o2_d0, f2py_rho2_d1, f2py_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2py_&
     &rd_d0, f2py_rd_d1)
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      real(kind=8) compute_force_cube(size(X, 1),size(X, 1),3)
      real(kind=8) compute_force_cubef2pywrap(size(X, 1),size(X, 1),3)
      end subroutine f2pywrap_gmdpd_f_compute_force_cube 
      subroutine f2pywrap_gmdpd_f_compute_pe (compute_pef2pywrap, comput&
     &e_pe, X, rho2, bl, ip_a, ip_b, rd, box, f2py_X_d0, f2py_X_d1, f2py&
     &_rho2_d0, f2py_rho2_d1, f2py_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2&
     &py_rd_d0, f2py_rd_d1)
      real(kind=8) compute_pe
      real(kind=8) ip_b
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      real(kind=8) compute_pef2pywrap
      end subroutine f2pywrap_gmdpd_f_compute_pe 
      subroutine f2pywrap_gmdpd_f_compute_ke (compute_kef2pywrap, comput&
     &e_ke, V, f2py_V_d0, f2py_V_d1)
      real(kind=8) compute_ke
      integer f2py_V_d0
      integer f2py_V_d1
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) compute_kef2pywrap
      end subroutine f2pywrap_gmdpd_f_compute_ke 
      subroutine f2pywrap_gmdpd_f_init_pos (init_posf2pywrap, init_pos, &
     &N, box)
      integer N
      real(kind=8) box(3,3)
      real(kind=8) init_pos(N,3)
      real(kind=8) init_posf2pywrap(N,3)
      end subroutine f2pywrap_gmdpd_f_init_pos 
      subroutine f2pywrap_gmdpd_f_init_vel (init_velf2pywrap, init_vel, &
     &N, kT)
      integer N
      real(kind=8) kT
      real(kind=8) init_vel(N,3)
      real(kind=8) init_velf2pywrap(N,3)
      end subroutine f2pywrap_gmdpd_f_init_vel 
      subroutine f2pywrap_gmdpd_f_euler_step (X, V, rho2, bl, nbt, ip_a,&
     & ip_b, rd, box, gama, kT, dt, f2py_X_d0, f2py_X_d1, f2py_V_d0, f2p&
     &y_V_d1, f2py_rho2_d0, f2py_rho2_d1, f2py_bl_d0, f2py_ip_a_d0, f2py&
     &_ip_a_d1, f2py_rd_d0, f2py_rd_d1)
      integer nbt
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      end subroutine f2pywrap_gmdpd_f_euler_step 
      subroutine f2pywrap_gmdpd_f_verlet_step (X, V, F, rho2, bl, nbt, i&
     &p_a, ip_b, rd, box, gama, kT, dt, f2py_X_d0, f2py_X_d1, f2py_V_d0,&
     & f2py_V_d1, f2py_F_d0, f2py_F_d1, f2py_rho2_d0, f2py_rho2_d1, f2py&
     &_bl_d0, f2py_ip_a_d0, f2py_ip_a_d1, f2py_rd_d0, f2py_rd_d1)
      integer nbt
      real(kind=8) ip_b
      real(kind=8) gama
      real(kind=8) kT
      real(kind=8) dt
      integer f2py_X_d0
      integer f2py_X_d1
      integer f2py_V_d0
      integer f2py_V_d1
      integer f2py_F_d0
      integer f2py_F_d1
      integer f2py_rho2_d0
      integer f2py_rho2_d1
      integer f2py_bl_d0
      integer f2py_ip_a_d0
      integer f2py_ip_a_d1
      integer f2py_rd_d0
      integer f2py_rd_d1
      real(kind=8) X(f2py_X_d0,f2py_X_d1)
      real(kind=8) V(f2py_V_d0,f2py_V_d1)
      real(kind=8) F(f2py_F_d0,f2py_F_d1)
      real(kind=8) rho2(f2py_rho2_d0,f2py_rho2_d1)
      integer bl(f2py_bl_d0)
      real(kind=8) ip_a(f2py_ip_a_d0,f2py_ip_a_d1)
      real(kind=8) rd(f2py_rd_d0,f2py_rd_d1)
      real(kind=8) box(3,3)
      end subroutine f2pywrap_gmdpd_f_verlet_step 
      subroutine f2pywrap_gmdpd_f_print_mat (A, f2py_A_d0, f2py_A_d1)
      integer f2py_A_d0
      integer f2py_A_d1
      real(kind=8) A(f2py_A_d0,f2py_A_d1)
      end subroutine f2pywrap_gmdpd_f_print_mat
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_gmdpd_f_randd,f2pywrap_gmdpd_f_wr,f2py&
     &wrap_gmdpd_f_wdd,f2pywrap_gmdpd_f_gaussnum,f2pywrap_gmdpd_f_local_&
     &density,f2pywrap_gmdpd_f_compute_force_fun,f2pywrap_gmdpd_f_comput&
     &e_force,f2pywrap_gmdpd_f_compute_force_cube,f2pywrap_gmdpd_f_compu&
     &te_pe,f2pywrap_gmdpd_f_compute_ke,f2pywrap_gmdpd_f_init_pos,f2pywr&
     &ap_gmdpd_f_init_vel,f2pywrap_gmdpd_f_euler_step,f2pywrap_gmdpd_f_v&
     &erlet_step,f2pywrap_gmdpd_f_print_mat)
      end subroutine f2pyinitgmdpd_f


